### ISSUE TITLE
Folder installation

### ISSUE THREAD

**Issue by christophe-natale** [goalgorilla/social_template#12]
Hello,
I need to install the distribution at the root of my public_html folder.
/public_html/core
not /public_html/html/core
I can't just deplace the files, I have an error message.
How can I do that ?

**Comment by ronaldtebrake** [comment]
Hi,

This template is just a starting point which you can obviously fork and alter to your needs, and there are some others that tried it before see some more information here:
https://www.drupal.org/project/social/issues/2898010
https://www.drupal.org/project/social/issues/2792543#comment-11591981

That should get you going.
