### ISSUE TITLE
Fields and display of content types

### ISSUE THREAD

**Issue by christophe-natale** [goalgorilla/social_template#13]
On a fresh install, I can't access the content type fields, even If I'm adminsitrator.
Is it normal ?
I just create a new content type and it's the same thing, I can't access the field screen..

**Comment by ronaldtebrake** [comment]
For Drupal related questions it would be better to not ask them on this repository since this is just the template.

I'd advice you to open up an issue here: https://www.drupal.org/project/issues/social

Regarding the above you need to enable the `fields_ui` module.
