### ISSUE TITLE
Problem with directory name case.  

### ISSUE THREAD

**Issue by AppreciateIT** [goalgorilla/social_template#6]
Had a problem when installing from this repo.  Built to a temp directory, then when copying files to proper location:

cp: cannot create directory '/var/www/html/modules/contrib/message/src/Plugin/views': File exists

There are both "Views" and "views" directories.  Wouldn't normally be a problem except installing into a container where the directory is mapped to a volume on a Mac.

Cheers,

Matt

**Comment by jaapjan** [comment]
Hi Matt,

I don't know what might be causing this. However on 9th May we released a new version of Open Social including update of the Message module to version 1.0-beta1. I see in this version they renamed "views" to "Views". 

Perhaps updating open social and thus Message by rebuilding solves your problem?

**Comment by jaapjan** [comment]
Closing the issue, but do let us know if you still have issues with this.
