### ISSUE TITLE
https://packages.drupal.org/8/packages.json unreachable

### ISSUE THREAD

**Issue by FleurJ** [goalgorilla/social_template#7]
Hi,

I'v been trying to install open social for a few days now, and I always get this error 

[Composer\Downloader\TransportException]
The "https://packages.drupal.org/8/packages.json" file could not be downloaded: failed to open stream: Network is unreachable

Any help?

thanks!

**Comment by jaapjan** [comment]
Closing this issue. See: https://www.drupal.org/node/2882230
